const actionTypes = Object.freeze({
    // Products
    FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
    FETCH_PRODUCT_STOP: "FETCH_PRODUCT_STOP",
    FETCH_PRODUCT_END: "FETCH_PRODUCT_END",

    //USER
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
    PROCESS_LOGOUT: "PROCESS_LOGOUT"

})

export default actionTypes;